#App data
org: <my_org> 
user: <my_githu_buser>

students: [classroom_rooster.csv]
assignment_name: [<my_assigments>]

#action: train
action: grade

openai_api_key: openai.api_key 
workers: 
- corregivos.domain.workers.Openai:
    model: text-davinci-003
    openai_api_key: $openai_api_key
    temperature: 1
    max_tokens: 1800
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    teachers: [<list_of_github_user_teachers>]
    prompt_suffix: $prompt_suffix
    completion_suffix: $completion_suffix
- corregivos.domain.workers.EndReviewWorker:
    base_model: davinci
    model_suffix: wollok
    training_file: $training_file
    output_training_file_data: $output_training_file_data
    commit_to_github: true

logging:
  version: 1
  disable_existing_loggers: false
  root:
    level: INFO
    handlers: [screen]
  handlers:
    screen:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  formatters:
    simple:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'  
